[database]

connection_string = "host=localhost port=5432 user=postgres password=admin dbname=auth_api_db sslmode=disable"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
###############################################################################
# HTTP server configuration

[http]

server_address = ":8080"
###############################################################################

[security]

jwt_secret = "your_secret_key"
###############################################################################